// THIS FILE IS AUTOGENERATED BY wb_intercon_gen
// ANY MANUAL CHANGES WILL BE LOST
module riscv_wb_intercon
   (input         wb_clk_i,
    input         wb_rst_i,
    input  [31:0] wb_ibus_adr_i,
    input  [31:0] wb_ibus_dat_i,
    input   [3:0] wb_ibus_sel_i,
    input         wb_ibus_we_i,
    input         wb_ibus_cyc_i,
    input         wb_ibus_stb_i,
    input   [2:0] wb_ibus_cti_i,
    input   [1:0] wb_ibus_bte_i,
    output [31:0] wb_ibus_dat_o,
    output        wb_ibus_ack_o,
    output        wb_ibus_err_o,
    output        wb_ibus_rty_o,
    input  [31:0] wb_dbus_adr_i,
    input  [31:0] wb_dbus_dat_i,
    input   [3:0] wb_dbus_sel_i,
    input         wb_dbus_we_i,
    input         wb_dbus_cyc_i,
    input         wb_dbus_stb_i,
    input   [2:0] wb_dbus_cti_i,
    input   [1:0] wb_dbus_bte_i,
    output [31:0] wb_dbus_dat_o,
    output        wb_dbus_ack_o,
    output        wb_dbus_err_o,
    output        wb_dbus_rty_o,
    output [31:0] wb_oc_mem_dbus_adr_o,
    output [31:0] wb_oc_mem_dbus_dat_o,
    output  [3:0] wb_oc_mem_dbus_sel_o,
    output        wb_oc_mem_dbus_we_o,
    output        wb_oc_mem_dbus_cyc_o,
    output        wb_oc_mem_dbus_stb_o,
    output  [2:0] wb_oc_mem_dbus_cti_o,
    output  [1:0] wb_oc_mem_dbus_bte_o,
    input  [31:0] wb_oc_mem_dbus_dat_i,
    input         wb_oc_mem_dbus_ack_i,
    input         wb_oc_mem_dbus_err_i,
    input         wb_oc_mem_dbus_rty_i,
    output [31:0] wb_oc_mem_ibus_adr_o,
    output [31:0] wb_oc_mem_ibus_dat_o,
    output  [3:0] wb_oc_mem_ibus_sel_o,
    output        wb_oc_mem_ibus_we_o,
    output        wb_oc_mem_ibus_cyc_o,
    output        wb_oc_mem_ibus_stb_o,
    output  [2:0] wb_oc_mem_ibus_cti_o,
    output  [1:0] wb_oc_mem_ibus_bte_o,
    input  [31:0] wb_oc_mem_ibus_dat_i,
    input         wb_oc_mem_ibus_ack_i,
    input         wb_oc_mem_ibus_err_i,
    input         wb_oc_mem_ibus_rty_i,
    output [31:0] wb_switch_adr_o,
    output  [7:0] wb_switch_dat_o,
    output  [3:0] wb_switch_sel_o,
    output        wb_switch_we_o,
    output        wb_switch_cyc_o,
    output        wb_switch_stb_o,
    output  [2:0] wb_switch_cti_o,
    output  [1:0] wb_switch_bte_o,
    input   [7:0] wb_switch_dat_i,
    input         wb_switch_ack_i,
    input         wb_switch_err_i,
    input         wb_switch_rty_i,
    output [31:0] wb_leds_adr_o,
    output  [7:0] wb_leds_dat_o,
    output  [3:0] wb_leds_sel_o,
    output        wb_leds_we_o,
    output        wb_leds_cyc_o,
    output        wb_leds_stb_o,
    output  [2:0] wb_leds_cti_o,
    output  [1:0] wb_leds_bte_o,
    input   [7:0] wb_leds_dat_i,
    input         wb_leds_ack_i,
    input         wb_leds_err_i,
    input         wb_leds_rty_i,
    output [31:0] wb_spi_lms_adr_o,
    output [31:0] wb_spi_lms_dat_o,
    output  [3:0] wb_spi_lms_sel_o,
    output        wb_spi_lms_we_o,
    output        wb_spi_lms_cyc_o,
    output        wb_spi_lms_stb_o,
    output  [2:0] wb_spi_lms_cti_o,
    output  [1:0] wb_spi_lms_bte_o,
    input  [31:0] wb_spi_lms_dat_i,
    input         wb_spi_lms_ack_i,
    input         wb_spi_lms_err_i,
    input         wb_spi_lms_rty_i,
    output [31:0] wb_lms_ctr_gpio_adr_o,
    output  [7:0] wb_lms_ctr_gpio_dat_o,
    output  [3:0] wb_lms_ctr_gpio_sel_o,
    output        wb_lms_ctr_gpio_we_o,
    output        wb_lms_ctr_gpio_cyc_o,
    output        wb_lms_ctr_gpio_stb_o,
    output  [2:0] wb_lms_ctr_gpio_cti_o,
    output  [1:0] wb_lms_ctr_gpio_bte_o,
    input   [7:0] wb_lms_ctr_gpio_dat_i,
    input         wb_lms_ctr_gpio_ack_i,
    input         wb_lms_ctr_gpio_err_i,
    input         wb_lms_ctr_gpio_rty_i,
    output [31:0] wb_Av_FIFO_Int0_adr_o,
    output [31:0] wb_Av_FIFO_Int0_dat_o,
    output  [3:0] wb_Av_FIFO_Int0_sel_o,
    output        wb_Av_FIFO_Int0_we_o,
    output        wb_Av_FIFO_Int0_cyc_o,
    output        wb_Av_FIFO_Int0_stb_o,
    output  [2:0] wb_Av_FIFO_Int0_cti_o,
    output  [1:0] wb_Av_FIFO_Int0_bte_o,
    input  [31:0] wb_Av_FIFO_Int0_dat_i,
    input         wb_Av_FIFO_Int0_ack_i,
    input         wb_Av_FIFO_Int0_err_i,
    input         wb_Av_FIFO_Int0_rty_i,
    output [31:0] wb_i2c_opencores_0_adr_o,
    output  [7:0] wb_i2c_opencores_0_dat_o,
    output  [3:0] wb_i2c_opencores_0_sel_o,
    output        wb_i2c_opencores_0_we_o,
    output        wb_i2c_opencores_0_cyc_o,
    output        wb_i2c_opencores_0_stb_o,
    output  [2:0] wb_i2c_opencores_0_cti_o,
    output  [1:0] wb_i2c_opencores_0_bte_o,
    input   [7:0] wb_i2c_opencores_0_dat_i,
    input         wb_i2c_opencores_0_ack_i,
    input         wb_i2c_opencores_0_err_i,
    input         wb_i2c_opencores_0_rty_i,
    output [31:0] wb_spi_1_DAC_adr_o,
    output [31:0] wb_spi_1_DAC_dat_o,
    output  [3:0] wb_spi_1_DAC_sel_o,
    output        wb_spi_1_DAC_we_o,
    output        wb_spi_1_DAC_cyc_o,
    output        wb_spi_1_DAC_stb_o,
    output  [2:0] wb_spi_1_DAC_cti_o,
    output  [1:0] wb_spi_1_DAC_bte_o,
    input  [31:0] wb_spi_1_DAC_dat_i,
    input         wb_spi_1_DAC_ack_i,
    input         wb_spi_1_DAC_err_i,
    input         wb_spi_1_DAC_rty_i,
    output [31:0] wb_spi_1_ADF_adr_o,
    output [31:0] wb_spi_1_ADF_dat_o,
    output  [3:0] wb_spi_1_ADF_sel_o,
    output        wb_spi_1_ADF_we_o,
    output        wb_spi_1_ADF_cyc_o,
    output        wb_spi_1_ADF_stb_o,
    output  [2:0] wb_spi_1_ADF_cti_o,
    output  [1:0] wb_spi_1_ADF_bte_o,
    input  [31:0] wb_spi_1_ADF_dat_i,
    input         wb_spi_1_ADF_ack_i,
    input         wb_spi_1_ADF_err_i,
    input         wb_spi_1_ADF_rty_i,
    output [31:0] wb_reset_gpio_adr_o,
    output  [7:0] wb_reset_gpio_dat_o,
    output  [3:0] wb_reset_gpio_sel_o,
    output        wb_reset_gpio_we_o,
    output        wb_reset_gpio_cyc_o,
    output        wb_reset_gpio_stb_o,
    output  [2:0] wb_reset_gpio_cti_o,
    output  [1:0] wb_reset_gpio_bte_o,
    input   [7:0] wb_reset_gpio_dat_i,
    input         wb_reset_gpio_ack_i,
    input         wb_reset_gpio_err_i,
    input         wb_reset_gpio_rty_i);

wire [31:0] wb_m2s_resize_switch_adr;
wire [31:0] wb_m2s_resize_switch_dat;
wire  [3:0] wb_m2s_resize_switch_sel;
wire        wb_m2s_resize_switch_we;
wire        wb_m2s_resize_switch_cyc;
wire        wb_m2s_resize_switch_stb;
wire  [2:0] wb_m2s_resize_switch_cti;
wire  [1:0] wb_m2s_resize_switch_bte;
wire [31:0] wb_s2m_resize_switch_dat;
wire        wb_s2m_resize_switch_ack;
wire        wb_s2m_resize_switch_err;
wire        wb_s2m_resize_switch_rty;
wire [31:0] wb_m2s_resize_leds_adr;
wire [31:0] wb_m2s_resize_leds_dat;
wire  [3:0] wb_m2s_resize_leds_sel;
wire        wb_m2s_resize_leds_we;
wire        wb_m2s_resize_leds_cyc;
wire        wb_m2s_resize_leds_stb;
wire  [2:0] wb_m2s_resize_leds_cti;
wire  [1:0] wb_m2s_resize_leds_bte;
wire [31:0] wb_s2m_resize_leds_dat;
wire        wb_s2m_resize_leds_ack;
wire        wb_s2m_resize_leds_err;
wire        wb_s2m_resize_leds_rty;
wire [31:0] wb_m2s_resize_lms_ctr_gpio_adr;
wire [31:0] wb_m2s_resize_lms_ctr_gpio_dat;
wire  [3:0] wb_m2s_resize_lms_ctr_gpio_sel;
wire        wb_m2s_resize_lms_ctr_gpio_we;
wire        wb_m2s_resize_lms_ctr_gpio_cyc;
wire        wb_m2s_resize_lms_ctr_gpio_stb;
wire  [2:0] wb_m2s_resize_lms_ctr_gpio_cti;
wire  [1:0] wb_m2s_resize_lms_ctr_gpio_bte;
wire [31:0] wb_s2m_resize_lms_ctr_gpio_dat;
wire        wb_s2m_resize_lms_ctr_gpio_ack;
wire        wb_s2m_resize_lms_ctr_gpio_err;
wire        wb_s2m_resize_lms_ctr_gpio_rty;
wire [31:0] wb_m2s_resize_i2c_opencores_0_adr;
wire [31:0] wb_m2s_resize_i2c_opencores_0_dat;
wire  [3:0] wb_m2s_resize_i2c_opencores_0_sel;
wire        wb_m2s_resize_i2c_opencores_0_we;
wire        wb_m2s_resize_i2c_opencores_0_cyc;
wire        wb_m2s_resize_i2c_opencores_0_stb;
wire  [2:0] wb_m2s_resize_i2c_opencores_0_cti;
wire  [1:0] wb_m2s_resize_i2c_opencores_0_bte;
wire [31:0] wb_s2m_resize_i2c_opencores_0_dat;
wire        wb_s2m_resize_i2c_opencores_0_ack;
wire        wb_s2m_resize_i2c_opencores_0_err;
wire        wb_s2m_resize_i2c_opencores_0_rty;
wire [31:0] wb_m2s_resize_reset_gpio_adr;
wire [31:0] wb_m2s_resize_reset_gpio_dat;
wire  [3:0] wb_m2s_resize_reset_gpio_sel;
wire        wb_m2s_resize_reset_gpio_we;
wire        wb_m2s_resize_reset_gpio_cyc;
wire        wb_m2s_resize_reset_gpio_stb;
wire  [2:0] wb_m2s_resize_reset_gpio_cti;
wire  [1:0] wb_m2s_resize_reset_gpio_bte;
wire [31:0] wb_s2m_resize_reset_gpio_dat;
wire        wb_s2m_resize_reset_gpio_ack;
wire        wb_s2m_resize_reset_gpio_err;
wire        wb_s2m_resize_reset_gpio_rty;

wb_mux
  #(.num_slaves (1),
    .MATCH_ADDR ({32'h00000000}),
    .MATCH_MASK ({32'hffff8000}))
 wb_mux_ibus
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_ibus_adr_i),
    .wbm_dat_i (wb_ibus_dat_i),
    .wbm_sel_i (wb_ibus_sel_i),
    .wbm_we_i  (wb_ibus_we_i),
    .wbm_cyc_i (wb_ibus_cyc_i),
    .wbm_stb_i (wb_ibus_stb_i),
    .wbm_cti_i (wb_ibus_cti_i),
    .wbm_bte_i (wb_ibus_bte_i),
    .wbm_dat_o (wb_ibus_dat_o),
    .wbm_ack_o (wb_ibus_ack_o),
    .wbm_err_o (wb_ibus_err_o),
    .wbm_rty_o (wb_ibus_rty_o),
    .wbs_adr_o ({wb_oc_mem_ibus_adr_o}),
    .wbs_dat_o ({wb_oc_mem_ibus_dat_o}),
    .wbs_sel_o ({wb_oc_mem_ibus_sel_o}),
    .wbs_we_o  ({wb_oc_mem_ibus_we_o}),
    .wbs_cyc_o ({wb_oc_mem_ibus_cyc_o}),
    .wbs_stb_o ({wb_oc_mem_ibus_stb_o}),
    .wbs_cti_o ({wb_oc_mem_ibus_cti_o}),
    .wbs_bte_o ({wb_oc_mem_ibus_bte_o}),
    .wbs_dat_i ({wb_oc_mem_ibus_dat_i}),
    .wbs_ack_i ({wb_oc_mem_ibus_ack_i}),
    .wbs_err_i ({wb_oc_mem_ibus_err_i}),
    .wbs_rty_i ({wb_oc_mem_ibus_rty_i}));

wb_mux
  #(.num_slaves (9),
    .MATCH_ADDR ({32'h00000000, 32'h000110b0, 32'h000110a0, 32'h00011040, 32'h00011060, 32'h000110c0, 32'h00011080, 32'h00011020, 32'h00011000}),
    .MATCH_MASK ({32'hffff8000, 32'hffffffe0, 32'hffffffe0, 32'hffffffe0, 32'hffffffe0, 32'hffffffe0, 32'hffffffe0, 32'hffffffe0, 32'hffffffe0}))
 wb_mux_dbus
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_dbus_adr_i),
    .wbm_dat_i (wb_dbus_dat_i),
    .wbm_sel_i (wb_dbus_sel_i),
    .wbm_we_i  (wb_dbus_we_i),
    .wbm_cyc_i (wb_dbus_cyc_i),
    .wbm_stb_i (wb_dbus_stb_i),
    .wbm_cti_i (wb_dbus_cti_i),
    .wbm_bte_i (wb_dbus_bte_i),
    .wbm_dat_o (wb_dbus_dat_o),
    .wbm_ack_o (wb_dbus_ack_o),
    .wbm_err_o (wb_dbus_err_o),
    .wbm_rty_o (wb_dbus_rty_o),
    .wbs_adr_o ({wb_oc_mem_dbus_adr_o, wb_m2s_resize_switch_adr, wb_m2s_resize_leds_adr, wb_spi_lms_adr_o, wb_m2s_resize_lms_ctr_gpio_adr, wb_Av_FIFO_Int0_adr_o, wb_m2s_resize_i2c_opencores_0_adr, wb_spi_1_DAC_adr_o, wb_spi_1_ADF_adr_o}),
    .wbs_dat_o ({wb_oc_mem_dbus_dat_o, wb_m2s_resize_switch_dat, wb_m2s_resize_leds_dat, wb_spi_lms_dat_o, wb_m2s_resize_lms_ctr_gpio_dat, wb_Av_FIFO_Int0_dat_o, wb_m2s_resize_i2c_opencores_0_dat, wb_spi_1_DAC_dat_o, wb_spi_1_ADF_dat_o}),
    .wbs_sel_o ({wb_oc_mem_dbus_sel_o, wb_m2s_resize_switch_sel, wb_m2s_resize_leds_sel, wb_spi_lms_sel_o, wb_m2s_resize_lms_ctr_gpio_sel, wb_Av_FIFO_Int0_sel_o, wb_m2s_resize_i2c_opencores_0_sel, wb_spi_1_DAC_sel_o, wb_spi_1_ADF_sel_o}),
    .wbs_we_o  ({wb_oc_mem_dbus_we_o, wb_m2s_resize_switch_we, wb_m2s_resize_leds_we, wb_spi_lms_we_o, wb_m2s_resize_lms_ctr_gpio_we, wb_Av_FIFO_Int0_we_o, wb_m2s_resize_i2c_opencores_0_we, wb_spi_1_DAC_we_o, wb_spi_1_ADF_we_o}),
    .wbs_cyc_o ({wb_oc_mem_dbus_cyc_o, wb_m2s_resize_switch_cyc, wb_m2s_resize_leds_cyc, wb_spi_lms_cyc_o, wb_m2s_resize_lms_ctr_gpio_cyc, wb_Av_FIFO_Int0_cyc_o, wb_m2s_resize_i2c_opencores_0_cyc, wb_spi_1_DAC_cyc_o, wb_spi_1_ADF_cyc_o}),
    .wbs_stb_o ({wb_oc_mem_dbus_stb_o, wb_m2s_resize_switch_stb, wb_m2s_resize_leds_stb, wb_spi_lms_stb_o, wb_m2s_resize_lms_ctr_gpio_stb, wb_Av_FIFO_Int0_stb_o, wb_m2s_resize_i2c_opencores_0_stb, wb_spi_1_DAC_stb_o, wb_spi_1_ADF_stb_o}),
    .wbs_cti_o ({wb_oc_mem_dbus_cti_o, wb_m2s_resize_switch_cti, wb_m2s_resize_leds_cti, wb_spi_lms_cti_o, wb_m2s_resize_lms_ctr_gpio_cti, wb_Av_FIFO_Int0_cti_o, wb_m2s_resize_i2c_opencores_0_cti, wb_spi_1_DAC_cti_o, wb_spi_1_ADF_cti_o}),
    .wbs_bte_o ({wb_oc_mem_dbus_bte_o, wb_m2s_resize_switch_bte, wb_m2s_resize_leds_bte, wb_spi_lms_bte_o, wb_m2s_resize_lms_ctr_gpio_bte, wb_Av_FIFO_Int0_bte_o, wb_m2s_resize_i2c_opencores_0_bte, wb_spi_1_DAC_bte_o, wb_spi_1_ADF_bte_o}),
    .wbs_dat_i ({wb_oc_mem_dbus_dat_i, wb_s2m_resize_switch_dat, wb_s2m_resize_leds_dat, wb_spi_lms_dat_i, wb_s2m_resize_lms_ctr_gpio_dat, wb_Av_FIFO_Int0_dat_i, wb_s2m_resize_i2c_opencores_0_dat, wb_spi_1_DAC_dat_i, wb_spi_1_ADF_dat_i}),
    .wbs_ack_i ({wb_oc_mem_dbus_ack_i, wb_s2m_resize_switch_ack, wb_s2m_resize_leds_ack, wb_spi_lms_ack_i, wb_s2m_resize_lms_ctr_gpio_ack, wb_Av_FIFO_Int0_ack_i, wb_s2m_resize_i2c_opencores_0_ack, wb_spi_1_DAC_ack_i, wb_spi_1_ADF_ack_i}),
    .wbs_err_i ({wb_oc_mem_dbus_err_i, wb_s2m_resize_switch_err, wb_s2m_resize_leds_err, wb_spi_lms_err_i, wb_s2m_resize_lms_ctr_gpio_err, wb_Av_FIFO_Int0_err_i, wb_s2m_resize_i2c_opencores_0_err, wb_spi_1_DAC_err_i, wb_spi_1_ADF_err_i}),
    .wbs_rty_i ({wb_oc_mem_dbus_rty_i, wb_s2m_resize_switch_rty, wb_s2m_resize_leds_rty, wb_spi_lms_rty_i, wb_s2m_resize_lms_ctr_gpio_rty, wb_Av_FIFO_Int0_rty_i, wb_s2m_resize_i2c_opencores_0_rty, wb_spi_1_DAC_rty_i, wb_spi_1_ADF_rty_i}));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_switch
   (.wbm_adr_i (wb_m2s_resize_switch_adr),
    .wbm_dat_i (wb_m2s_resize_switch_dat),
    .wbm_sel_i (wb_m2s_resize_switch_sel),
    .wbm_we_i  (wb_m2s_resize_switch_we),
    .wbm_cyc_i (wb_m2s_resize_switch_cyc),
    .wbm_stb_i (wb_m2s_resize_switch_stb),
    .wbm_cti_i (wb_m2s_resize_switch_cti),
    .wbm_bte_i (wb_m2s_resize_switch_bte),
    .wbm_dat_o (wb_s2m_resize_switch_dat),
    .wbm_ack_o (wb_s2m_resize_switch_ack),
    .wbm_err_o (wb_s2m_resize_switch_err),
    .wbm_rty_o (wb_s2m_resize_switch_rty),
    .wbs_adr_o (wb_switch_adr_o),
    .wbs_dat_o (wb_switch_dat_o),
    .wbs_we_o  (wb_switch_we_o),
    .wbs_cyc_o (wb_switch_cyc_o),
    .wbs_stb_o (wb_switch_stb_o),
    .wbs_cti_o (wb_switch_cti_o),
    .wbs_bte_o (wb_switch_bte_o),
    .wbs_dat_i (wb_switch_dat_i),
    .wbs_ack_i (wb_switch_ack_i),
    .wbs_err_i (wb_switch_err_i),
    .wbs_rty_i (wb_switch_rty_i));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_leds
   (.wbm_adr_i (wb_m2s_resize_leds_adr),
    .wbm_dat_i (wb_m2s_resize_leds_dat),
    .wbm_sel_i (wb_m2s_resize_leds_sel),
    .wbm_we_i  (wb_m2s_resize_leds_we),
    .wbm_cyc_i (wb_m2s_resize_leds_cyc),
    .wbm_stb_i (wb_m2s_resize_leds_stb),
    .wbm_cti_i (wb_m2s_resize_leds_cti),
    .wbm_bte_i (wb_m2s_resize_leds_bte),
    .wbm_dat_o (wb_s2m_resize_leds_dat),
    .wbm_ack_o (wb_s2m_resize_leds_ack),
    .wbm_err_o (wb_s2m_resize_leds_err),
    .wbm_rty_o (wb_s2m_resize_leds_rty),
    .wbs_adr_o (wb_leds_adr_o),
    .wbs_dat_o (wb_leds_dat_o),
    .wbs_we_o  (wb_leds_we_o),
    .wbs_cyc_o (wb_leds_cyc_o),
    .wbs_stb_o (wb_leds_stb_o),
    .wbs_cti_o (wb_leds_cti_o),
    .wbs_bte_o (wb_leds_bte_o),
    .wbs_dat_i (wb_leds_dat_i),
    .wbs_ack_i (wb_leds_ack_i),
    .wbs_err_i (wb_leds_err_i),
    .wbs_rty_i (wb_leds_rty_i));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_lms_ctr_gpio
   (.wbm_adr_i (wb_m2s_resize_lms_ctr_gpio_adr),
    .wbm_dat_i (wb_m2s_resize_lms_ctr_gpio_dat),
    .wbm_sel_i (wb_m2s_resize_lms_ctr_gpio_sel),
    .wbm_we_i  (wb_m2s_resize_lms_ctr_gpio_we),
    .wbm_cyc_i (wb_m2s_resize_lms_ctr_gpio_cyc),
    .wbm_stb_i (wb_m2s_resize_lms_ctr_gpio_stb),
    .wbm_cti_i (wb_m2s_resize_lms_ctr_gpio_cti),
    .wbm_bte_i (wb_m2s_resize_lms_ctr_gpio_bte),
    .wbm_dat_o (wb_s2m_resize_lms_ctr_gpio_dat),
    .wbm_ack_o (wb_s2m_resize_lms_ctr_gpio_ack),
    .wbm_err_o (wb_s2m_resize_lms_ctr_gpio_err),
    .wbm_rty_o (wb_s2m_resize_lms_ctr_gpio_rty),
    .wbs_adr_o (wb_lms_ctr_gpio_adr_o),
    .wbs_dat_o (wb_lms_ctr_gpio_dat_o),
    .wbs_we_o  (wb_lms_ctr_gpio_we_o),
    .wbs_cyc_o (wb_lms_ctr_gpio_cyc_o),
    .wbs_stb_o (wb_lms_ctr_gpio_stb_o),
    .wbs_cti_o (wb_lms_ctr_gpio_cti_o),
    .wbs_bte_o (wb_lms_ctr_gpio_bte_o),
    .wbs_dat_i (wb_lms_ctr_gpio_dat_i),
    .wbs_ack_i (wb_lms_ctr_gpio_ack_i),
    .wbs_err_i (wb_lms_ctr_gpio_err_i),
    .wbs_rty_i (wb_lms_ctr_gpio_rty_i));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_i2c_opencores_0
   (.wbm_adr_i (wb_m2s_resize_i2c_opencores_0_adr),
    .wbm_dat_i (wb_m2s_resize_i2c_opencores_0_dat),
    .wbm_sel_i (wb_m2s_resize_i2c_opencores_0_sel),
    .wbm_we_i  (wb_m2s_resize_i2c_opencores_0_we),
    .wbm_cyc_i (wb_m2s_resize_i2c_opencores_0_cyc),
    .wbm_stb_i (wb_m2s_resize_i2c_opencores_0_stb),
    .wbm_cti_i (wb_m2s_resize_i2c_opencores_0_cti),
    .wbm_bte_i (wb_m2s_resize_i2c_opencores_0_bte),
    .wbm_dat_o (wb_s2m_resize_i2c_opencores_0_dat),
    .wbm_ack_o (wb_s2m_resize_i2c_opencores_0_ack),
    .wbm_err_o (wb_s2m_resize_i2c_opencores_0_err),
    .wbm_rty_o (wb_s2m_resize_i2c_opencores_0_rty),
    .wbs_adr_o (wb_i2c_opencores_0_adr_o),
    .wbs_dat_o (wb_i2c_opencores_0_dat_o),
    .wbs_we_o  (wb_i2c_opencores_0_we_o),
    .wbs_cyc_o (wb_i2c_opencores_0_cyc_o),
    .wbs_stb_o (wb_i2c_opencores_0_stb_o),
    .wbs_cti_o (wb_i2c_opencores_0_cti_o),
    .wbs_bte_o (wb_i2c_opencores_0_bte_o),
    .wbs_dat_i (wb_i2c_opencores_0_dat_i),
    .wbs_ack_i (wb_i2c_opencores_0_ack_i),
    .wbs_err_i (wb_i2c_opencores_0_err_i),
    .wbs_rty_i (wb_i2c_opencores_0_rty_i));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_reset_gpio
   (.wbm_adr_i (wb_m2s_resize_reset_gpio_adr),
    .wbm_dat_i (wb_m2s_resize_reset_gpio_dat),
    .wbm_sel_i (wb_m2s_resize_reset_gpio_sel),
    .wbm_we_i  (wb_m2s_resize_reset_gpio_we),
    .wbm_cyc_i (wb_m2s_resize_reset_gpio_cyc),
    .wbm_stb_i (wb_m2s_resize_reset_gpio_stb),
    .wbm_cti_i (wb_m2s_resize_reset_gpio_cti),
    .wbm_bte_i (wb_m2s_resize_reset_gpio_bte),
    .wbm_dat_o (wb_s2m_resize_reset_gpio_dat),
    .wbm_ack_o (wb_s2m_resize_reset_gpio_ack),
    .wbm_err_o (wb_s2m_resize_reset_gpio_err),
    .wbm_rty_o (wb_s2m_resize_reset_gpio_rty),
    .wbs_adr_o (wb_reset_gpio_adr_o),
    .wbs_dat_o (wb_reset_gpio_dat_o),
    .wbs_we_o  (wb_reset_gpio_we_o),
    .wbs_cyc_o (wb_reset_gpio_cyc_o),
    .wbs_stb_o (wb_reset_gpio_stb_o),
    .wbs_cti_o (wb_reset_gpio_cti_o),
    .wbs_bte_o (wb_reset_gpio_bte_o),
    .wbs_dat_i (wb_reset_gpio_dat_i),
    .wbs_ack_i (wb_reset_gpio_ack_i),
    .wbs_err_i (wb_reset_gpio_err_i),
    .wbs_rty_i (wb_reset_gpio_rty_i));

endmodule
